#!/bin/bash
USE_NAM_ONLY=true

AGENT_STYLE_USAGE=true
AGENT_STYLE_SIZE=3
AGENT_STYLE_NUM_NETS=3
AGENT_STYLE_COMMON_WEIGHT=0.5
AGENT_STYLE_DEFENSIVE_WEIGHT=0.8
AGENT_STYLE_AGGRESSIVE_WEIGHT=0.2
AGENT_STYLE_MEDIUM_EQUAL_WEIGHT=false

USE_TIME_PENALTY=true
TIME_PENALTY_VALUE=0.1

#observation
LOOKAHEAD_NUM=20
LOOKAHEAD_THETA=20
LIDAR_NUM=30

#agent/policy
WORLD_DT=0.05
ACTION_DT=0.001
USE_CONTINUOUS_BPS=true
ACTION_DIM=3
ALLOW_BOTH_FEET=false
ALLOW_NEG_TORQUE=true
ALWAYS_POS_VEL=0

#E_c penalty
USE_E_C_PENALTY=true
#off-course penalty
OFF_COURSE_PENALTY_WEIGHT=2
#negative velocity BPS penalty
NEG_VEL_BPS_PENALTY_WEIGHT=1


python train_main.py --config_name=config_style \
    agent.exp_name=$EXP_NAME \
